"""Расширение модели FinancialRecord

Revision ID: 52adb17ace00
Revises: bec83eac3181
Create Date: 2025-02-06 18:55:49.354350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52adb17ace00'
down_revision: Union[str, None] = 'bec83eac3181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_records', sa.Column('liquidity_check', sa.Boolean(), nullable=True))
    op.add_column('financial_records', sa.Column('last_interest_change_date', sa.DateTime(), nullable=True))
    op.add_column('financial_records', sa.Column('penalty_fee', sa.Float(), nullable=True))
    op.add_column('financial_records', sa.Column('flexible_interest', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_records', 'flexible_interest')
    op.drop_column('financial_records', 'penalty_fee')
    op.drop_column('financial_records', 'last_interest_change_date')
    op.drop_column('financial_records', 'liquidity_check')
    # ### end Alembic commands ###
