"""Добавлены комиссии, штрафы, история ставок

Revision ID: 54190609fe58
Revises: 52adb17ace00
Create Date: 2025-02-06 21:55:55.811499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54190609fe58'
down_revision: Union[str, None] = '52adb17ace00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_records', sa.Column('fee', sa.Float(), nullable=True))
    op.add_column('financial_records', sa.Column('penalty', sa.Float(), nullable=True))
    op.add_column('financial_records', sa.Column('interest_rate_changes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_records', 'interest_rate_changes')
    op.drop_column('financial_records', 'penalty')
    op.drop_column('financial_records', 'fee')
    # ### end Alembic commands ###
