"""Recreate financial records schema

Revision ID: 5b4d223f2cfa
Revises: 994659864b5b
Create Date: 2025-02-05 00:02:37.443478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4d223f2cfa'
down_revision: Union[str, None] = '994659864b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_records', sa.Column('min_amount', sa.Float(), nullable=True))
    op.add_column('financial_records', sa.Column('max_amount', sa.Float(), nullable=True))
    op.add_column('financial_records', sa.Column('withdrawal_penalty', sa.Boolean(), nullable=True))
    op.add_column('financial_records', sa.Column('refinance_available', sa.Boolean(), nullable=True))
    op.add_column('financial_records', sa.Column('alternative_deposits', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_records', 'alternative_deposits')
    op.drop_column('financial_records', 'refinance_available')
    op.drop_column('financial_records', 'withdrawal_penalty')
    op.drop_column('financial_records', 'max_amount')
    op.drop_column('financial_records', 'min_amount')
    # ### end Alembic commands ###
